name: Invisible Code Scan

on:
  push: 
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test step
        run: echo "CI/CD is working!"